BlogDevice/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

resources :posts do
  resources :comments
end

   root 'posts#index'

end

BlogDevice/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user.present?
        can :create, Post
        can :manage, Post, :user_id => user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

BlogDevice/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

BlogDevice/app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :image, MediaUploader
	belongs_to :user
	has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

BlogDevice/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  mount_uploader :photo, PhotoUploader
  has_many :posts
end

BlogDevice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo, :bio])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo, :bio])
  end
end

BlogDevice/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

BlogDevice/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show ]

  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

BlogDevice/app/helpers/comments_helper.rb
module CommentsHelper
end

BlogDevice/app/helpers/posts_helper.rb
module PostsHelper
end

BlogDevice/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BlogDevice/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

BlogDevice/app/views/posts/index.html.erb
<h1>WTM Guayacanes </h1>

<ul>
<% @posts.each do |post| %>
  <li>
    <h2><%= link_to post.title, post %></h2>
    <% if can? :manage, post %>
      <p><%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </li>
<% end %>
</ul>


<br>
<% if can? :create, Post %>
  <%= link_to 'Crear un Post', new_post_path %>
<% end %>

BlogDevice/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

BlogDevice/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

	<h2>
	  <%= @post.title %>
	</h2>
	<%= image_tag @post.image %>

	<p>
	  <%= @post.body %>
	</p>

	<p>
	  by <%= @post.user.name %>
	  <%= image_tag @post.user.photo.thumb %>
	</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p

	<%= link_to 'Edit', edit_comment_path(@comment) %> 
	<%= link_to 'Back', comments_path %>

<% end %>

<h2>Añadir comentario:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p> 

	<%= f.submit%>
<% end %>
	<% if can? :manage, @post %>
		<%= link_to 'Edit', edit_post_path(@post) %> |
	<% end %>
		<%= link_to 'Back', posts_path %>
	